# Generated by Django 3.0.4 on 2020-09-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='Router',
        ),
    ]
