# Generated by Django 3.0.4 on 2020-09-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20200926_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='hostname',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
